### ISSUE TITLE
Wrong format of config file flake8 reads

### ISSUE THREAD

**Issue by fakegermano** [carstencodes/flake518#1]
When we put something like

```
ignore = [ "D203", "W503" ]
```

in the pyproject.toml `[tool.flake8]` configuration, when we check the verbose logs from flake8 with `flake518 -vvv --count`

We can see the following:
```
flake8.options.config     MainProcess     87 DEBUG    Option "ignore" returned value: "['D203', 'W503']"
flake8.options.config     MainProcess     87 DEBUG    "['D203', 'W503']" has been normalized to ["['D203'", "'W503']"] for option "ignore"
```

which ends up putting the wrong ignore list:
```
flake8.options.aggregator MainProcess     87 DEBUG    Merged default ignore list: ['W504', 'E123', 'E24', 'E226', 'E121', 'W503', 'E704', 'E126']
[...]
flake8.options.aggregator MainProcess     87 DEBUG    Overriding default value of (['W504', 'E123', 'E24', 'E226', 'E121', 'W503', 'E704', 'E126']) for "ignore" with (["['D203'", "'W503']"])
```

As you can see, flake8 does weird things with the configuration provided.

I suspect the temporary file created from reading the toml configuration is using the wrong format for the list, and flake8 is not parsing it correctly.

**Comment by carstencodes** [comment]
Yeah, I see the issue.

According to the implementation of `ConfigParser` at python (cf. https://github.com/python/cpython/blob/9ab2b48f2b89f1119bc22aafc8a90f8588f7472f/Lib/configparser.py#L935) the value will be written as
```python
"{}{}".format(key, value)
```
which in case of a list brings up 
['D203', 'W503']

Flake8 instead expects 
D203, W503 
as depicted in https://flake8.pycqa.org/en/latest/user/configuration.html.

So, after reading the toml file and before dumping the dictionary, the values must be updated.

Lists must be converted to strings.

I think, i can deal with that. It might take a little while.

**Comment by carstencodes** [comment]
@fakegermano Version 1.1.0 should fix this. I'm adding tests in the future. Therefore I'll leave the issue open.

**Comment by fakegermano** [comment]
Seems great!
The configuration now is properly loaded but for some reason it's not enforcing the "ignore" rule for me (although the debug shows it being overwritten). Its probably a separate issue, but thanks for this!

**Comment by fakegermano** [comment]
Ah, found it, I was using `flake8` directly. It worked now using the `flake518` binary! Thanks!

**Comment by carstencodes** [comment]
Tests will be tracked in #5
