### ISSUE TITLE
Deprecate flake518

### ISSUE THREAD

**Issue by carstencodes** [carstencodes/flake518#10]
The successor of flake518 will be a new project with a working draft title called 'pyr' (python project runner), which will use plug-ins for every tool that does not consider the pyproject.toml.
With the release of pyr 1.0, flake518 will be deprecated.

**Comment by jannismain** [comment]
are you saying I _shouldn't_ start using `flake518` to get rid of setup.cfg?

**Comment by carstencodes** [comment]
No, I'm not saying this.

I've just found some other projects not using pyproject.toml. The plan is to create a new wrapper project and finally make flake518 a wrapper or alias for this.

This will take some time, at least three months to do so. After that, I am going to deprecate flake518 leaving nothing but a small script to start the new executable and maybe emitting a deprecation warning.

Until then, feel free to use flake518 and beyond that date, feel free to use it either, but note that after that point, the Main focus will be the new project.

**Comment by jannismain** [comment]
I see. Thanks for the clarification :)

**Comment by proinsias** [comment]
Great utility! Any update about pyr? Happy to continue to use this project in the meantime!

**Comment by carstencodes** [comment]
I am currently far behind my schedule. I think, a first working draft is about to be released in September

**Comment by carstencodes** [comment]
This issue will be closed as there will be no deprecation. I will add an entrypoint to this package and the program will call it
